### ISSUE TITLE
java.lang.IllegalArgumentException: Wrong type! Position = -1

### ISSUE THREAD

**Issue by taishuhongye** [Aspsine/IRecyclerView#52]
代码中没看到什么异常。没有getAdapter()方法的调用。可能是和kotlin或者mvvvm有冲突。
陈年bug了。求求您，辛苦一下，看看吧。

java.lang.IllegalArgumentException: Wrong type! Position = -1
    at com.aspsine.irecyclerview.g.getItemViewType(WrapperAdapter.java:134)
    at com.aspsine.irecyclerview.g.onViewAttachedToWindow(WrapperAdapter.java:101)
    at android.support.v7.widget.RecyclerView.f(RecyclerView.java:7270)
    at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:855)
    at android.support.v7.widget.ChildHelper.a(ChildHelper.java:107)
    at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8336)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
    at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1573)
    at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1517)
    at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1331)
    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1075)
    at android.support.v7.widget.RecyclerView.a(RecyclerView.java:1832)
    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5067)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
    at android.view.Choreographer.doCallbacks(Choreographer.java:847)
    at android.view.Choreographer.doFrame(Choreographer.java:771)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1027)
    at android.os.Handler.handleCallback(Handler.java:809)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7555)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by varunjain0888** [comment]
I am also facing same issue with Concat adapter

**Comment by gaoyangcr7** [comment]
facing same issue
